general:
  project_name: untitled_project
  camera_type: FLIR
  camera_model: BFS-U3-200S6C-C
camera_settings:
  camera_1:
    exposure_time: 90000.0
    gain_level: 1.83
    gamma: 0.8
  camera_3:
    exposure_time: 90000.0
    gain_level: 1.83
    gamma: 0.8
exif_data:
  camera_1:
    Make: FLIR
    Model: BFS-U3-200S6C-C
    SerialNumber: '21447407'
    Lens: MPZ
    CameraSerialNumber: '21447407'
    LensManufacturer: Computar
    LensModel: 35.0 f / 2.2
    FocalLength: '35.0'
    FocalLengthIn35mmFormat: '95.0'
  camera_3:
    Make: FLIR
    Model: BFS-U3-200S6C-C
    SerialNumber: '21188171'
    Lens: MPZ
    CameraSerialNumber: '21188171'
    LensManufacturer: Computar
    LensModel: 35.0 f / 2.2
    FocalLength: '35.0'
    FocalLengthIn35mmFormat: '95.0'
    